import { useState, useEffect, useRef } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Loader2,
  Copy,
  Check,
  Eye,
  EyeOff,
  RefreshCw,
  ExternalLink,
  Shield,
  AlertTriangle,
  CheckCircle2,
  Circle,
} from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { ptBR } from "date-fns/locale";

// Facebook icon component
const FacebookIcon = ({ className }: { className?: string }) => (
  <svg className={className} viewBox="0 0 24 24" fill="currentColor">
    <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
  </svg>
);

interface FacebookSettings {
  facebook_webhook_token: string | null;
  facebook_verify_token: string | null;
  facebook_page_access_token: string | null;
  facebook_app_secret: string | null;
  facebook_last_lead_at: string | null;
  facebook_leads_count: number | null;
}

type ConfigStatus = "configured" | "partial" | "not_configured";

export function FacebookLeadsSettings() {
  const { companyId } = useAuth();
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [settings, setSettings] = useState<FacebookSettings | null>(null);
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [showAccessToken, setShowAccessToken] = useState(false);
  const [showAppSecret, setShowAppSecret] = useState(false);
  const hasAutoGenerated = useRef(false);

  // Form state
  const [pageAccessToken, setPageAccessToken] = useState("");
  const [appSecret, setAppSecret] = useState("");

  useEffect(() => {
    if (companyId) {
      fetchSettings();
    }
  }, [companyId]);

  // Auto-generate tokens if they don't exist
  useEffect(() => {
    if (
      companyId &&
      settings &&
      !settings.facebook_webhook_token &&
      !isRegenerating &&
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true;
      regenerateTokens();
    }
  }, [companyId, settings, isRegenerating]);

  const fetchSettings = async () => {
    if (!companyId) return;

    try {
      setIsLoading(true);
      const { data, error } = await supabase
        .from("lyn_company")
        .select(
          "facebook_webhook_token, facebook_verify_token, facebook_page_access_token, facebook_app_secret, facebook_last_lead_at, facebook_leads_count"
        )
        .eq("id", companyId)
        .single();

      if (error) throw error;

      // Type assertion since we know the structure
      const typedData = data as unknown as FacebookSettings;
      setSettings(typedData);
      setPageAccessToken(typedData?.facebook_page_access_token || "");
      setAppSecret(typedData?.facebook_app_secret || "");
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : "Erro desconhecido";
      toast({
        title: "Erro ao carregar configurações",
        description: errorMessage,
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSave = async () => {
    if (!companyId) return;

    try {
      setIsSaving(true);

      const updateData: Record<string, string | null> = {
        facebook_page_access_token: pageAccessToken.trim() || null,
        facebook_app_secret: appSecret.trim() || null,
      };

      const { error } = await supabase
        .from("lyn_company")
        .update(updateData)
        .eq("id", companyId);

      if (error) throw error;

      toast({
        title: "Credenciais salvas",
        description: "As credenciais do Facebook foram atualizadas.",
      });

      fetchSettings();
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : "Erro desconhecido";
      toast({
        title: "Erro ao salvar",
        description: errorMessage,
        variant: "destructive",
      });
    } finally {
      setIsSaving(false);
    }
  };

  const copyToClipboard = async (text: string, field: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(field);
      setTimeout(() => setCopiedField(null), 2000);
      toast({
        title: "Copiado!",
        description: `${field} copiado para a área de transferência.`,
      });
    } catch (err) {
      toast({
        title: "Erro ao copiar",
        description: "Não foi possível copiar para a área de transferência.",
        variant: "destructive",
      });
    }
  };

  const regenerateTokens = async () => {
    if (!companyId) return;

    try {
      setIsRegenerating(true);

      // Call the regenerate function
      const { error } = await supabase.rpc("regenerate_facebook_tokens", {
        company_uuid: companyId,
      });

      if (error) throw error;

      toast({
        title: "Tokens gerados",
        description: "A URL do webhook está pronta para uso.",
      });

      fetchSettings();
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : "Erro desconhecido";
      toast({
        title: "Erro ao gerar tokens",
        description: errorMessage,
        variant: "destructive",
      });
    } finally {
      setIsRegenerating(false);
    }
  };

  const getConfigStatus = (): ConfigStatus => {
    if (!settings) return "not_configured";
    if (settings.facebook_page_access_token && settings.facebook_webhook_token) {
      return settings.facebook_app_secret ? "configured" : "partial";
    }
    return "not_configured";
  };

  const configStatus = getConfigStatus();

  // Build the webhook URL
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "";
  const webhookUrl = settings?.facebook_webhook_token
    ? `${supabaseUrl}/functions/v1/facebook-leads-webhook/${settings.facebook_webhook_token}`
    : "";

  // Check which steps are complete
  const hasWebhookUrl = !!settings?.facebook_webhook_token;
  const hasPageToken = !!settings?.facebook_page_access_token;

  if (isLoading) {
    return (
      <Card className="shadow-lyn">
        <CardContent className="flex items-center justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="shadow-lyn">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <FacebookIcon className="h-5 w-5 text-[#1877F2]" />
              Facebook Lead Ads
            </CardTitle>
            <CardDescription>
              Receba leads automaticamente dos seus anúncios do Facebook
            </CardDescription>
          </div>
          <Badge
            variant={
              configStatus === "configured"
                ? "default"
                : configStatus === "partial"
                  ? "secondary"
                  : "outline"
            }
            className={
              configStatus === "configured"
                ? "bg-green-500/10 text-green-600 border-green-200"
                : configStatus === "partial"
                  ? "bg-amber-500/10 text-amber-600 border-amber-200"
                  : ""
            }
          >
            {configStatus === "configured"
              ? "Configurado"
              : configStatus === "partial"
                ? "Parcialmente Configurado"
                : "Não Configurado"}
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* Stats Section */}
        {settings?.facebook_leads_count !== null &&
          (settings?.facebook_leads_count ?? 0) > 0 && (
            <div className="flex gap-6 p-4 bg-muted/50 rounded-lg">
              <div>
                <p className="text-2xl font-bold text-foreground">
                  {settings?.facebook_leads_count}
                </p>
                <p className="text-sm text-muted-foreground">Leads recebidos</p>
              </div>
              {settings?.facebook_last_lead_at && (
                <div>
                  <p className="text-sm font-medium text-foreground">Último lead</p>
                  <p className="text-sm text-muted-foreground">
                    {formatDistanceToNow(new Date(settings.facebook_last_lead_at), {
                      addSuffix: true,
                      locale: ptBR,
                    })}
                  </p>
                </div>
              )}
            </div>
          )}

        {/* STEP 1: Webhook URL Section - ALWAYS VISIBLE */}
        <div className="space-y-4 p-4 border rounded-lg bg-muted/30">
          <div className="flex items-center gap-2">
            {hasWebhookUrl ? (
              <CheckCircle2 className="h-5 w-5 text-green-600" />
            ) : (
              <Circle className="h-5 w-5 text-muted-foreground" />
            )}
            <h3 className="font-medium text-foreground">
              Passo 1: Configurar Webhook no Facebook
            </h3>
          </div>

          {isRegenerating ? (
            <div className="flex items-center gap-2 py-4">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span className="text-sm text-muted-foreground">Gerando URL do webhook...</span>
            </div>
          ) : hasWebhookUrl ? (
            <>
              <div className="space-y-2">
                <Label>URL do Webhook (Callback URL)</Label>
                <div className="flex gap-2">
                  <Input
                    value={webhookUrl}
                    readOnly
                    className="font-mono text-xs bg-background"
                  />
                  <Button
                    type="button"
                    variant="outline"
                    size="icon"
                    onClick={() => copyToClipboard(webhookUrl, "URL")}
                  >
                    {copiedField === "URL" ? (
                      <Check className="h-4 w-4 text-green-600" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </Button>
                </div>
                <p className="text-xs text-muted-foreground">
                  Cole esta URL no campo "Callback URL" do Facebook Developers
                </p>
              </div>

              <div className="space-y-2">
                <Label>Token de Verificação (Verify Token)</Label>
                <div className="flex gap-2">
                  <Input
                    value={settings?.facebook_verify_token || ""}
                    readOnly
                    className="font-mono bg-background"
                  />
                  <Button
                    type="button"
                    variant="outline"
                    size="icon"
                    onClick={() =>
                      copyToClipboard(settings?.facebook_verify_token || "", "Token")
                    }
                  >
                    {copiedField === "Token" ? (
                      <Check className="h-4 w-4 text-green-600" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    size="icon"
                    onClick={regenerateTokens}
                    disabled={isRegenerating}
                    title="Regenerar tokens"
                  >
                    {isRegenerating ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <RefreshCw className="h-4 w-4" />
                    )}
                  </Button>
                </div>
                <p className="text-xs text-muted-foreground">
                  Cole este token no campo "Verify Token" do Facebook Developers
                </p>
              </div>
            </>
          ) : (
            <div className="py-2">
              <Button onClick={regenerateTokens} disabled={isRegenerating}>
                {isRegenerating && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Gerar URL do Webhook
              </Button>
            </div>
          )}
        </div>

        {/* Instructions Accordion - Expanded by default for unconfigured users */}
        <Accordion
          type="single"
          collapsible
          className="w-full"
          defaultValue={configStatus === "not_configured" ? "instructions" : undefined}
        >
          <AccordionItem value="instructions" className="border rounded-lg px-4">
            <AccordionTrigger className="hover:no-underline">
              <span className="flex items-center gap-2 text-sm">
                <ExternalLink className="h-4 w-4" />
                Como configurar no Facebook Developers
              </span>
            </AccordionTrigger>
            <AccordionContent>
              <ol className="space-y-4 text-sm text-muted-foreground pb-4">
                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex items-center justify-center">
                    1
                  </span>
                  <div>
                    <p className="text-foreground font-medium">Criar ou acessar seu App</p>
                    <p>
                      Acesse{" "}
                      <a
                        href="https://developers.facebook.com/apps"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-primary hover:underline"
                      >
                        Meta for Developers
                      </a>{" "}
                      e selecione ou crie um aplicativo do tipo "Empresarial"
                    </p>
                  </div>
                </li>

                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex items-center justify-center">
                    2
                  </span>
                  <div>
                    <p className="text-foreground font-medium">Adicionar Webhooks</p>
                    <p>
                      No painel do app, vá em "Adicionar Produto" e selecione "Webhooks"
                    </p>
                  </div>
                </li>

                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex items-center justify-center">
                    3
                  </span>
                  <div>
                    <p className="text-foreground font-medium">Configurar Webhook para Page</p>
                    <p>
                      Selecione "Page" no dropdown, clique em "Subscribe to this object"
                    </p>
                  </div>
                </li>

                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex items-center justify-center">
                    4
                  </span>
                  <div>
                    <p className="text-foreground font-medium">Preencher campos</p>
                    <p>
                      Cole a <strong>URL do Webhook</strong> no campo "Callback URL" e o{" "}
                      <strong>Token de Verificação</strong> no campo "Verify Token"
                    </p>
                  </div>
                </li>

                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex items-center justify-center">
                    5
                  </span>
                  <div>
                    <p className="text-foreground font-medium">Inscrever no leadgen</p>
                    <p>
                      Na lista de campos, encontre e marque "leadgen", depois clique em "Subscribe"
                    </p>
                  </div>
                </li>

                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex items-center justify-center">
                    6
                  </span>
                  <div>
                    <p className="text-foreground font-medium">Obter Page Access Token</p>
                    <p>
                      Acesse o{" "}
                      <a
                        href="https://developers.facebook.com/tools/explorer"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-primary hover:underline"
                      >
                        Graph API Explorer
                      </a>
                      , selecione seu App, gere um token com as permissões{" "}
                      <code className="text-xs bg-muted px-1 rounded">leads_retrieval</code>,{" "}
                      <code className="text-xs bg-muted px-1 rounded">pages_manage_ads</code> e{" "}
                      <code className="text-xs bg-muted px-1 rounded">pages_read_engagement</code>
                    </p>
                  </div>
                </li>

                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-semibold flex items-center justify-center">
                    7
                  </span>
                  <div>
                    <p className="text-foreground font-medium">Testar a integração</p>
                    <p>
                      Use a{" "}
                      <a
                        href="https://developers.facebook.com/tools/lead-ads-testing"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-primary hover:underline"
                      >
                        ferramenta de teste de Lead Ads
                      </a>{" "}
                      para gerar um lead de teste e verificar se aparece na aba Leads
                    </p>
                  </div>
                </li>
              </ol>
            </AccordionContent>
          </AccordionItem>
        </Accordion>

        {/* STEP 2: Credentials Form */}
        <div className="space-y-4 p-4 border rounded-lg">
          <div className="flex items-center gap-2">
            {hasPageToken ? (
              <CheckCircle2 className="h-5 w-5 text-green-600" />
            ) : (
              <Circle className="h-5 w-5 text-muted-foreground" />
            )}
            <h3 className="font-medium text-foreground">
              Passo 2: Adicionar suas Credenciais
            </h3>
          </div>

          <div className="space-y-2">
            <Label htmlFor="facebook_page_access_token">
              Page Access Token *
            </Label>
            <div className="relative">
              <Input
                id="facebook_page_access_token"
                type={showAccessToken ? "text" : "password"}
                placeholder="EAAxxxxxxxxxxxxxxxxxx..."
                value={pageAccessToken}
                onChange={(e) => setPageAccessToken(e.target.value)}
                className="pr-10"
              />
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7"
                onClick={() => setShowAccessToken(!showAccessToken)}
              >
                {showAccessToken ? (
                  <EyeOff className="h-4 w-4" />
                ) : (
                  <Eye className="h-4 w-4" />
                )}
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              Necessário para buscar dados completos dos leads da Graph API
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="facebook_app_secret" className="flex items-center gap-2">
              <Shield className="h-4 w-4" />
              App Secret (Recomendado)
            </Label>
            <div className="relative">
              <Input
                id="facebook_app_secret"
                type={showAppSecret ? "text" : "password"}
                placeholder="Opcional - para validação de assinatura"
                value={appSecret}
                onChange={(e) => setAppSecret(e.target.value)}
                className="pr-10"
              />
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7"
                onClick={() => setShowAppSecret(!showAppSecret)}
              >
                {showAppSecret ? (
                  <EyeOff className="h-4 w-4" />
                ) : (
                  <Eye className="h-4 w-4" />
                )}
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              O App Secret valida que as requisições vem realmente do Facebook (HMAC SHA256)
            </p>
          </div>

          {/* Warning if no app secret */}
          {!settings?.facebook_app_secret &&
            settings?.facebook_page_access_token && (
              <div className="flex items-start gap-2 p-3 bg-amber-500/10 border border-amber-200 rounded-lg">
                <AlertTriangle className="h-4 w-4 text-amber-600 mt-0.5 flex-shrink-0" />
                <p className="text-xs text-amber-700">
                  Recomendamos configurar o App Secret para maior segurança.
                  Sem ele, não é possível validar a origem das requisições.
                </p>
              </div>
            )}

          <Button onClick={handleSave} disabled={isSaving} className="w-full">
            {isSaving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Salvar Credenciais
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
